name: Amplify Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Configure Amplify CLI
      run: npm install -g @aws-amplify/cli

    - name: Assume IAM Role
      id: sts
      run: |
        ROLE_ARN="arn:aws:iam::894085200796:role/service-role/AmplifySSRLoggingRole-d2zavuz57t6j05"  # Replace with your IAM role ARN
      

    - name: Amplify Init
      run: amplify init

    - name: Amplify Pull
      run: amplify pull --appId d2lilztwk3650x 

    - name: Build and Deploy to Amplify
      run: npm run build  # Replace with your build command

    - name: Deploy to Amplify
      run: amplify publish   # Replace with your Amplify deployment command
