name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

     # Change to your desired region

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

  
    - name: Check AWS CLI Version
      run: aws --version
 

    - name: Test AWS CLI
      run: aws s3 ls s3://s3gitlab-server 
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      shell: /usr/bin/bash -e -x {0}
        

    
